name: emrsurvival
channels:
  - rdkit
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2020.6.20
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.11.5
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.2
  - icu=58.2
  - importlib_metadata=0.23
  - intel-openmp=2019.1
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.0
  - kiwisolver=1.0.1
  - libboost=1.65.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.35
  - libprotobuf=3.12.3
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - more-itertools=7.2.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - nccl=1.3.5
  - ncurses=6.1
  - networkx=2.2
  - ninja=1.8.2
  - notebook=6.0.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.42
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pixman=0.34.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.12.3
  - ptyprocess=0.6.0
  - py-boost=1.65.1
  - pycparser=2.19
  - pygments=2.4.2
  - pyparsing=2.3.0
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - python=3.6.7
  - python-dateutil=2.7.5
  - python_abi=3.6
  - pytz=2018.7
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - rdkit=2018.09.1.0
  - readline=7.0
  - scikit-learn=0.20.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setproctitle=1.1.10
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.25.3
  - statsmodels=0.10.1
  - tbb=2020.0
  - tbb4py=2020.0
  - tensorboardx=2.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - tqdm=4.47.0
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.32.3
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - ase==3.19.1
    - astunparse==1.6.3
    - autograd==1.3
    - autograd-gamma==0.4.2
    - blis==0.4.1
    - cachetools==4.1.1
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - configparser==5.0.1
    - cymem==2.0.3
    - dataclasses==0.7
    - docker-pycreds==0.4.0
    - easydict==1.9
    - en-core-web-sm==2.3.1
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.5
    - gitpython==3.1.12
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - grpcio==1.30.0
    - h5py==2.10.0
    - idna==2.10
    - isodate==0.6.0
    - joblib==0.16.0
    - keras-preprocessing==1.1.2
    - lifelines==0.25.0
    - llvmlite==0.33.0
    - markdown==3.2.2
    - murmurhash==1.0.2
    - nltk==3.5
    - numba==0.50.1
    - numpy==1.19.1
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - packaging==20.4
    - parmap==1.5.2
    - pathtools==0.1.2
    - pip==20.1.1
    - plac==1.1.3
    - plyfile==0.7.1
    - preshed==3.0.2
    - promise==2.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - rdflib==4.2.2
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacremoses==0.0.43
    - scipy==1.5.2
    - sentencepiece==0.1.91
    - sentry-sdk==0.19.5
    - setuptools==49.2.0
    - shap==0.39.0
    - shortuuid==1.0.1
    - slicer==0.0.7
    - smmap==3.0.4
    - spacy==2.3.2
    - srsly==1.0.2
    - subprocess32==3.5.4
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - thinc==7.4.1
    - tokenizers==0.8.1rc1
    - torch==1.5.1+cu101
    - torch-cluster==1.5.5
    - torch-geometric==1.5.0
    - torch-scatter==2.0.5
    - torch-sparse==0.6.6
    - torch-spline-conv==1.2.0
    - torchvision==0.6.1+cu101
    - transformers==3.0.2
    - urllib3==1.25.9
    - wandb==0.10.13
    - wasabi==0.7.1
    - watchdog==0.10.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xlrd==1.2.0
    - xlsxwriter==1.2.9

